AWSTemplateFormatVersion: "2010-09-09"
Description: Lambda to store front pressed events Kinesis stream to Dynamo
Parameters:
    Stack:
        Description: Stack name
        Type: String
        Default: cms-fronts
    App:
        Description: Application name
        Type: String
        Default: front-pressed-lambda
    Stage:
        Description: Stage name
        Type: String
        AllowedValues:
            - CODE
            - PROD
        Default: CODE
    FrontendAccountId:
        Description: Frontend account
        Type: String
    SESLambda:
        Description: Lambda used to send emails
        Type: String
Mappings:
    StageMap:
        PROD:
            ReadThroughput: 7
            WriteThroughput: 7
        CODE:
            ReadThroughput: 5
            WriteThroughput: 5
Resources:
    AssumedRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Statement:
                    - Effect: Allow
                      Principal:
                        AWS:
                            "Fn::Join": [ "", [
                                "arn:aws:iam::",
                                { "Ref": "FrontendAccountId" },
                                ":root"
                            ]]
                      Action: "sts:AssumeRole"
            Path: /
    DynamoDBPolicy:
        Type: AWS::IAM::Policy
        Properties:
            PolicyName: DynamoDBPolicy
            PolicyDocument:
                Version: "2012-10-17"
                Statement:
                    -   Effect: Allow
                        Action:
                            - "dynamodb:PutItem"
                            - "dynamodb:UpdateItem"
                        Resource:
                            - Fn::Join:
                                - ""
                                -
                                    - "arn:aws:dynamodb:"
                                    - Ref: "AWS::Region"
                                    - ":"
                                    - Ref: "AWS::AccountId"
                                    - ":table/"
                                    - Ref: DynamoDBTable
                            - Fn::Join:
                                - ""
                                -
                                    - "arn:aws:dynamodb:"
                                    - Ref: "AWS::Region"
                                    - ":"
                                    - Ref: "AWS::AccountId"
                                    - ":table/"
                                    - Ref: ErrorsTable
            Roles:
                - Ref: AssumedRole
    DynamoDBTable:
        Type: AWS::DynamoDB::Table
        Properties:
            AttributeDefinitions:
                -
                    AttributeName: stageName
                    AttributeType: S
                -
                    AttributeName: frontId
                    AttributeType: S
            KeySchema:
                -
                    AttributeName: stageName
                    KeyType: HASH
                -
                    AttributeName: frontId
                    KeyType: RANGE
            ProvisionedThroughput:
                ReadCapacityUnits:
                    Fn::FindInMap:
                        - StageMap
                        - Ref: Stage
                        - ReadThroughput
                WriteCapacityUnits:
                    Fn::FindInMap:
                        - StageMap
                        - Ref: Stage
                        - WriteThroughput
    ErrorsTable:
        Type: AWS::DynamoDB::Table
        Properties:
            AttributeDefinitions:
                -
                    AttributeName: errorId
                    AttributeType: S
                -
                    AttributeName: time
                    AttributeType: N
                -
                    AttributeName: expirationTime
                    AttributeType: N
                -
                    AttributeName: frontId
                    AttributeType: S
            KeySchema:
                -
                    AttributeName: errorId
                    KeyType: HASH
                -
                    AttributeName: time
                    KeyType: RANGE
            ProvisionedThroughput:
                ReadCapacityUnits:
                    Fn::FindInMap:
                        - StageMap
                        - Ref: Stage
                        - ReadThroughput
                WriteCapacityUnits:
                    Fn::FindInMap:
                        - StageMap
                        - Ref: Stage
                        - WriteThroughput
            TimeToLiveSpecification:
                AttributeName: expirationTime
                Enabled: true
    SendEmail:
        Type: AWS::IAM::Policy
        Properties:
            PolicyName: SendEmail
            PolicyDocument:
                Version: "2012-10-17"
                Statement:
                    -   Effect: Allow
                        Action:
                            - "lambda:InvokeFunction"
                        Resource:
                            - Fn::Join:
                                - ""
                                - - "arn:aws:lambda:"
                                  - Ref: AWS::Region
                                  - ":"
                                  - Ref: AWS::AccountId
                                  - ":function:"
                                  - Ref: SESLambda
            Roles:
                - Ref: AssumedRole
