AWSTemplateFormatVersion: "2010-09-09"
Description: Lambda to store front pressed events Kinesis stream to Dynamo
Parameters:
    Stack:
        Description: Stack name
        Type: String
        Default: cms-fronts
    App:
        Description: Application name
        Type: String
        Default: front-pressed-lambda
    Stage:
        Description: Stage name
        Type: String
        AllowedValues:
            - CODE
            - PROD
        Default: CODE
    EventSourceKinesisArn:
        Description: Kinesis stream emitting front press events
        Type: String
    FrontendRoleToAssume:
        Description: Frontend Role to assume for cross account policies
        Type: String
Mappings:
    StageMap:
        PROD:
            ReadThroughput: 7
            WriteThroughput: 7
        CODE:
            ReadThroughput: 5
            WriteThroughput: 5
Resources:
    ExecutionRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                              - lambda.amazonaws.com
                      Action: "sts:AssumeRole"
            Path: /
    KinesisPolicy:
        Type: AWS::IAM::Policy
        Properties:
            PolicyName: consumeKinesis
            PolicyDocument:
                Statement:
                    -   Effect: "Allow"
                        Action:
                            - "kinesis:GetRecords"
                            - "kinesis:GetShardIterator"
                            - "kinesis:DescribeStream"
                            - "kinesis:ListStreams"
                        Resource:
                            -
                                Ref: "EventSourceKinesisArn"
            Roles:
                - Ref: "ExecutionRole"

    DynamoDBPolicy:
        Type: AWS::IAM::Policy
        Properties:
            PolicyName: DynamoDBPolicy
            PolicyDocument:
                Version: "2012-10-17"
                Statement:
                    -   Effect: "Allow"
                        Action:
                            - "dynamodb:PutItem"
                            - "dynamodb:UpdateItem"
                        Resource:
                            - Fn::Join:
                                - ""
                                -
                                    - "arn:aws:dynamodb:"
                                    - Ref: "AWS::Region"
                                    - ":"
                                    - Ref: "AWS::AccountId"
                                    - ":table/"
                                    - Ref: "DynamoDBTable"
            Roles:
                - Ref: "ExecutionRole"
    DynamoDBTable:
        Type: "AWS::DynamoDB::Table"
        Properties:
            AttributeDefinitions:
                -
                    AttributeName: "id"
                    AttributeType: "S"
            KeySchema:
                -
                    AttributeName: "id"
                    KeyType: "HASH"
            ProvisionedThroughput:
                ReadCapacityUnits:
                    Fn::FindInMap:
                        - "StageMap"
                        - Ref: "Stage"
                        - "ReadThroughput"
                WriteCapacityUnits:
                    Fn::FindInMap:
                        - "StageMap"
                        - Ref: "Stage"
                        - "WriteThroughput"
    Lambda:
        Type: AWS::Lambda::Function
        Properties:
            Code:
                S3Bucket: front-pressed-lambda-dist
                S3Key:
                    "Fn::Join":
                        - "/"
                        -
                            - Ref: Stage
                            - artifact.zip
            Description: Store events from Kinesos into Dynamo
            Handler: index.handler
            MemorySize: 128
            Role:
                "Fn::GetAtt": ["ExecutionRole", "Arn"]
            Runtime: nodejs
            Timeout: 60
    EventSource:
        Type: AWS::Lambda::EventSourceMapping
        Properties:
            BatchSize: 10
            Enabled: true
            EventSourceArn:
                Ref: EventSourceKinesisArn
            FunctionName:
                Ref: Lambda
            StartingPosition: LATEST
