name: build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main # merge

jobs:
  build:
    runs-on: ubuntu-latest

    permissions: # required by aws-actions/configure-aws-credentials
      id-token: write
      contents: read
      # Required for `guardian/actions-riff-raff`
      pull-requests: write

    steps:
      # Seed the build number with last number from TeamCity.
      # This env var is used by the JS, and SBT builds, and guardian/actions-riff-raff.
      # Set the value early, rather than `buildNumberOffset` in guardian/actions-riff-raff, to ensure each usage has the same number.
      # For some reason, it's not possible to mutate GITHUB_RUN_NUMBER, so set BUILD_NUMBER instead.
      - name: Set BUILD_NUMBER environment variable
        run: |
          LAST_TEAMCITY_BUILD=199
          echo "BUILD_NUMBER=$(( $GITHUB_RUN_NUMBER + $LAST_TEAMCITY_BUILD ))" >> $GITHUB_ENV
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
         node-version-file: '.nvmrc'
         cache: npm
         cache-dependency-path: 'package-lock.json'

      - name: Install NPM dependencies
        run: npm clean-install --legacy-peer-deps # --legacy-peer-deps avoids babel dep. related failures

      - name: Run lint
        run: npm run lint

      - name: Test JS
        run: npm test

      - name: Build JS
        run: npm run bundle

      - name: AWS Auth
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1

      - uses: guardian/actions-riff-raff@v3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: front-pressed-lambda
          buildNumber: ${{ env.BUILD_NUMBER }}
          configPath: riff-raff.yaml
          contentDirectories: |
            front-pressed-lambda:
              - dist/front-pressed-lambda.zip
            front-pressed-lambda-cloudformation:
              - cloudformation/frontend.yml

      - uses: guardian/actions-riff-raff@v3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: front-pressed-lambda::cloudformation
          config: |
            stacks:
              - cms-fronts
            regions:
              - eu-west-1
            allowedStages:
              - CODE
              - PROD
            deployments:
              cloudformation:
                type: cloud-formation
                app: front-pressed-lambda
                parameters:
                  templatePath: cmsfronts.yml
                  createStackIfAbsent: false
          contentDirectories: |
            cloudformation:
              - cloudformation/cmsfronts.yml
